Repository sighupio/gatekeeper-policy-manager, pull requests merged in 2022-10, with the labels that each got.

#453 fix(helm): remove unused test script
  chart/templates/tests/test-connection.yaml
Labels: enhancement

#467 Fix multicluster report download
  app/app.py
  app/web-client/src/pages/Constraints/Component.tsx
Labels: bug

#468 Fix: improve constraint violations table
  app/web-client/src/pages/Constraints/Component.tsx
Labels: bug, enhancement

#476 feat: added logout page
  app/app.py
  app/web-client/src/App.tsx
  app/web-client/src/components/Header/Component.tsx
  app/web-client/src/pages/Logout/Component.tsx
  app/web-client/src/pages/Logout/index.ts
Labels: enhancement

#479 add support for additional ingress labels
  chart/README.md
  chart/templates/ingress.yaml
  chart/values.yaml
Labels: enhancement
